
package mvcgenerala;

import java.awt.Color;
import java.util.Random;
import static javax.swing.DropMode.valueOf;
import javax.swing.JButton;


public class Vista extends javax.swing.JFrame {

    
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        labelDeTiradas = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMostrarNombreLabel = new javax.swing.JLabel();
        btnDado2 = new javax.swing.JButton();
        btnDado3 = new javax.swing.JButton();
        btnDado4 = new javax.swing.JButton();
        btnDado5 = new javax.swing.JButton();
        btnDado6 = new javax.swing.JButton();
        btnDado1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnTirarDados = new javax.swing.JButton();
        btnPasarTurno = new javax.swing.JButton();
        txtMostrarNombreLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtJugador1 = new javax.swing.JTextField();
        txtJugador3 = new javax.swing.JTextField();
        txtJugador2 = new javax.swing.JTextField();
        txtJugadorFull = new javax.swing.JTextField();
        txtJugador4 = new javax.swing.JTextField();
        txtJugador5 = new javax.swing.JTextField();
        txtJugador6 = new javax.swing.JTextField();
        txtJugadorPoker = new javax.swing.JTextField();
        txtJugadorEscalera = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtJugadorGenerala = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtCpu4 = new javax.swing.JTextField();
        txtCpu3 = new javax.swing.JTextField();
        txtCpu2 = new javax.swing.JTextField();
        txtCpu1 = new javax.swing.JTextField();
        txtCpu6 = new javax.swing.JTextField();
        txtCpu5 = new javax.swing.JTextField();
        txtCpuEscalera = new javax.swing.JTextField();
        txtCpuFull = new javax.swing.JTextField();
        txtCpuGenerala = new javax.swing.JTextField();
        txtCpuPoker = new javax.swing.JTextField();
        btnReiniciarJuego = new javax.swing.JButton();
        btnCerrarJuego = new javax.swing.JButton();
        btnCalcularSumatoria = new javax.swing.JButton();
        labelResultadoes = new javax.swing.JLabel();

        jButton5.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Juego de la generala", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre del jugador:");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(102, 204, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        labelDeTiradas.setForeground(new java.awt.Color(0, 0, 0));
        labelDeTiradas.setText("Dados ------------------------Tiradas que quedan: 3");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("El turno es de: ");

        txtMostrarNombreLabel.setForeground(new java.awt.Color(0, 0, 0));
        txtMostrarNombreLabel.setText("***********");

        btnDado2.setBackground(new java.awt.Color(204, 204, 204));
        btnDado2.setText("Dado 2");
        btnDado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDado2ActionPerformed(evt);
            }
        });

        btnDado3.setBackground(new java.awt.Color(204, 204, 204));
        btnDado3.setText("Dado 3");
        btnDado3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDado3ActionPerformed(evt);
            }
        });

        btnDado4.setBackground(new java.awt.Color(204, 204, 204));
        btnDado4.setText("Dado 4");
        btnDado4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDado4ActionPerformed(evt);
            }
        });

        btnDado5.setBackground(new java.awt.Color(204, 204, 204));
        btnDado5.setText("Dado 5");
        btnDado5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDado5ActionPerformed(evt);
            }
        });

        btnDado6.setBackground(new java.awt.Color(204, 204, 204));
        btnDado6.setText("Dado 6");
        btnDado6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDado6ActionPerformed(evt);
            }
        });

        btnDado1.setBackground(new java.awt.Color(204, 204, 204));
        btnDado1.setText("Dado 1");
        btnDado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDado1ActionPerformed(evt);
            }
        });

        btnTirarDados.setBackground(new java.awt.Color(255, 153, 153));
        btnTirarDados.setText("Tirar los dados");
        btnTirarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTirarDadosActionPerformed(evt);
            }
        });

        btnPasarTurno.setBackground(new java.awt.Color(102, 153, 255));
        btnPasarTurno.setText("Pasar Turno");
        btnPasarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasarTurnoActionPerformed(evt);
            }
        });

        txtMostrarNombreLabel2.setForeground(new java.awt.Color(0, 0, 0));
        txtMostrarNombreLabel2.setText("Jugador");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("1");

        txtJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJugador1ActionPerformed(evt);
            }
        });

        txtJugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJugador2ActionPerformed(evt);
            }
        });

        txtJugador6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJugador6ActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("2");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("3");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("4");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("5");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("6");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Escalera");

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Full");

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Poker");

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Generala");

        txtJugadorGenerala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJugadorGeneralaActionPerformed(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("CPU");

        btnReiniciarJuego.setText("Reiniciar juego");
        btnReiniciarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarJuegoActionPerformed(evt);
            }
        });

        btnCerrarJuego.setText("Cerrar juego");
        btnCerrarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarJuegoActionPerformed(evt);
            }
        });

        btnCalcularSumatoria.setText("Calcular resultados");
        btnCalcularSumatoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularSumatoriaActionPerformed(evt);
            }
        });

        labelResultadoes.setForeground(new java.awt.Color(0, 0, 0));
        labelResultadoes.setText("Los resultados son:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMostrarNombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDeTiradas, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTirarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnDado1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDado2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnPasarTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnDado5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnDado3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnDado4, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                .addComponent(btnDado6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(303, 303, 303)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtJugador5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtJugador3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtJugador2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtJugador4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtJugador6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel13))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtJugadorFull, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtJugadorGenerala, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtJugadorEscalera, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCpuGenerala, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCpuFull, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCpuEscalera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCpuPoker, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(372, 372, 372)
                                .addComponent(txtJugadorPoker, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCpu1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCpu2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCpu3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCpu4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCpu5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCpu6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelResultadoes)
                                    .addComponent(btnCalcularSumatoria, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(259, 259, 259))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addComponent(txtMostrarNombreLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReiniciarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCerrarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMostrarNombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDeTiradas)
                    .addComponent(jLabel16)
                    .addComponent(txtMostrarNombreLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCpu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDado1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDado2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnDado4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDado3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCpu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtJugador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCpu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCpu4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtJugador4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCpu5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtJugador5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCpu6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtJugador6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11)))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtJugadorPoker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(txtCpuPoker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(btnTirarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDado6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDado5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                        .addComponent(btnPasarTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtJugadorEscalera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCpuEscalera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtJugadorFull, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCpuFull, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtJugadorGenerala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(txtCpuGenerala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnCalcularSumatoria, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelResultadoes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCerrarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReiniciarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {                                           
        //esto es del boton guardar nombre, solo eso, luego hace que cambie el label de abajo
        nombre = txtNombre.getText();
        txtMostrarNombreLabel.setText(nombre);
        txtMostrarNombreLabel2.setText(nombre);
        
        

    }                                          
    String nombre = "";
    //bandera para que cambie el turno
    int banderaTiradas = 3, turnoDeJoC = 1;
    private void btnTirarDadosActionPerformed(java.awt.event.ActionEvent evt) {                                              
        //creamos array de botones
        JButton[] botones = {btnDado1, btnDado2, btnDado3, btnDado4, btnDado5, btnDado6};
        //creamos objeto aleaotrio
        Random aleatorio = new Random();
        //esto entra primero, se fija si cumple lo de la bandera
        //el for va pasando por el arreglo, y crea un valor y se lo coloca al dado
        //al terminar con el arreglo baja un numero de las tiradas/banderas q queda
        if (banderaTiradas > 0) {
            for (int i = 0; i < botones.length; i++) {
                if (!retenido[i]) { // solo cambia si NO está retenido
                    int valor = aleatorio.nextInt(6) + 1;
                    botones[i].setText("" + valor);
                }
            }
            //esto cambia el numero de tiradas con texto
            banderaTiradas--;
            labelDeTiradas.setText("Dados ------------------------Tiradas que quedan: " + banderaTiradas);
            
            
        }


    }                                             
    boolean[] retenido = {false, false, false, false, false, false}; // para 6 dados
    private void btnDado4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        retenido[3] = !retenido[3]; // alterna entre true y false
        if (retenido[3]) {
            btnDado4.setBackground(Color.GREEN); // indicador visual
        } else {
            btnDado4.setBackground(Color.LIGHT_GRAY);
        }
    }                                        

    private void btnDado3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        retenido[2] = !retenido[2]; // alterna entre true y false
        if (retenido[2]) {
            btnDado3.setBackground(Color.GREEN); // indicador visual
        } else {
            btnDado3.setBackground(Color.LIGHT_GRAY);
        }
    }                                        

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {                                        

    }                                       

    private void txtJugador6ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void txtJugadorGeneralaActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void btnReiniciarJuegoActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        //limpiar texto
        //ejemplo
        txtMostrarNombreLabel.setText("***********");
        txtMostrarNombreLabel2.setText("Jugador");

        banderaTiradas = 3;
        labelDeTiradas.setText("Dados ------------------------Tiradas que quedan: " + banderaTiradas);
        //limpiamos los dados
        JButton[] botones = {btnDado1, btnDado2, btnDado3, btnDado4, btnDado5, btnDado6};
        for (int i = 0; i < 6; i++) {
            retenido[i] = false;
            botones[i].setBackground(Color.LIGHT_GRAY); // Vuelve al color original
        }
        
            btnDado1.setText("Dado 1"); 
            btnDado2.setText("Dado 2"); 
            btnDado3.setText("Dado 3"); 
            btnDado4.setText("Dado 4"); 
            btnDado5.setText("Dado 5"); 
            btnDado6.setText("Dado 6"); 
        //cambiamos el label de resultado
        labelResultadoes.setText("Los resultados son: ");
    }                                                 

    private void btnCerrarJuegoActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void btnPasarTurnoActionPerformed(java.awt.event.ActionEvent evt) {                                              

        //cambio de bandera y label de turno
        banderaTiradas = 3;
        if (turnoDeJoC == 1) {
            txtMostrarNombreLabel.setText("cpu");
            labelDeTiradas.setText("Dados ------------------------Tiradas que quedan: " + banderaTiradas);
            turnoDeJoC = 0;
        } else {
            turnoDeJoC = 1;
            labelDeTiradas.setText("Dados ------------------------Tiradas que quedan: " + banderaTiradas);
            txtMostrarNombreLabel.setText(nombre);
        }
        //--------------------------------------------------------

        // Reinicia las retenciones y colores
        JButton[] botones = {btnDado1, btnDado2, btnDado3, btnDado4, btnDado5, btnDado6};
        for (int i = 0; i < 6; i++) {
            retenido[i] = false;
            botones[i].setBackground(Color.LIGHT_GRAY); // Vuelve al color original
        }

    }                                             

    private void btnDado2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        retenido[1] = !retenido[1]; // alterna entre true y false
        if (retenido[1]) {
            btnDado2.setBackground(Color.GREEN); // indicador visual
        } else {
            btnDado2.setBackground(Color.LIGHT_GRAY);
        }
    }                                        

    private void btnDado1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        //esto es por si tocas el boton y queda verde, y luego no lo puedas usar
        retenido[0] = !retenido[0]; // alterna entre true y false
        if (retenido[0]) {
            btnDado1.setBackground(Color.GREEN); // indicador visual
        } else {
            btnDado1.setBackground(Color.LIGHT_GRAY);
        }
    }                                        

    private void btnDado5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        retenido[4] = !retenido[4]; // alterna entre true y false
        if (retenido[4]) {
            btnDado5.setBackground(Color.GREEN); // indicador visual
        } else {
            btnDado5.setBackground(Color.LIGHT_GRAY);
        }
    }                                        

    private void btnDado6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        retenido[5] = !retenido[5]; // alterna entre true y false
        if (retenido[5]) {
            btnDado6.setBackground(Color.GREEN); // indicador visual
        } else {
            btnDado6.setBackground(Color.LIGHT_GRAY);
        }
    }                                        

    private void txtJugador1ActionPerformed(java.awt.event.ActionEvent evt) {                                            

    }                                           

    private void txtJugador2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           
    //esto hace q si le das a calcular no se rompa, ya q estamos transformando el texto en numero, pero si no hay nada se rompe
    //si no tiene nada retorna un 0, usando try catch
    private int parseOrZero(String texto) {
        if (texto == null || texto.trim().isEmpty()) {
            return 0;
        }
        try {
            return Integer.parseInt(texto.trim());
        } catch (NumberFormatException e) {
            return 0;
        }
    }
    private void btnCalcularSumatoriaActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        //calcular la suma de todo con lo q esta arriba
        int numero1 = parseOrZero(txtJugador1.getText());
        int numero2 = parseOrZero(txtJugador2.getText());
        int numero3 = parseOrZero(txtJugador3.getText());
        int numero4 = parseOrZero(txtJugador4.getText());
        int numero5 = parseOrZero(txtJugador5.getText());
        int numero6 = parseOrZero(txtJugador6.getText());
        int numeropoker = parseOrZero(txtJugadorPoker.getText());
        int numeroescalera = parseOrZero(txtJugadorEscalera.getText());
        int numerofull = parseOrZero(txtJugadorFull.getText());
        int numeroGenerala = parseOrZero(txtJugadorGenerala.getText());

        int numero12 = parseOrZero(txtCpu1.getText());
        int numero22 = parseOrZero(txtCpu2.getText());
        int numero32 = parseOrZero(txtCpu3.getText());
        int numero42 = parseOrZero(txtCpu4.getText());
        int numero52 = parseOrZero(txtCpu5.getText());
        int numero62 = parseOrZero(txtCpu6.getText());
        int numeropoker2 = parseOrZero(txtCpuPoker.getText());
        int numeroescalera2 = parseOrZero(txtCpuEscalera.getText());
        int numerofull2 = parseOrZero(txtCpuFull.getText());
        int numeroGenerala2 = parseOrZero(txtCpuGenerala.getText());

        int resultadoJugador1 = numero1 + numero2 + numero3 + numero4 + numero5 + numero6 + numeropoker + numeroescalera + numerofull + numeroGenerala;
        int resultadoCpu1 = numero12 + numero22 + numero32 + numero42 + numero52 + numero62 + numeropoker2 + numeroescalera2 + numerofull2 + numeroGenerala2;
        labelResultadoes.setText("Los resultados son: " + resultadoJugador1 + " Resultado de la Cpu es:" + resultadoCpu1);
    }                                                    
    public void setMostrarNombre() {

    }


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnCalcularSumatoria;
    private javax.swing.JButton btnCerrarJuego;
    private javax.swing.JButton btnDado1;
    private javax.swing.JButton btnDado2;
    private javax.swing.JButton btnDado3;
    private javax.swing.JButton btnDado4;
    private javax.swing.JButton btnDado5;
    private javax.swing.JButton btnDado6;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnPasarTurno;
    private javax.swing.JButton btnReiniciarJuego;
    private javax.swing.JButton btnTirarDados;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelDeTiradas;
    private javax.swing.JLabel labelResultadoes;
    private javax.swing.JTextField txtCpu1;
    private javax.swing.JTextField txtCpu2;
    private javax.swing.JTextField txtCpu3;
    private javax.swing.JTextField txtCpu4;
    private javax.swing.JTextField txtCpu5;
    private javax.swing.JTextField txtCpu6;
    private javax.swing.JTextField txtCpuEscalera;
    private javax.swing.JTextField txtCpuFull;
    private javax.swing.JTextField txtCpuGenerala;
    private javax.swing.JTextField txtCpuPoker;
    private javax.swing.JTextField txtJugador1;
    private javax.swing.JTextField txtJugador2;
    private javax.swing.JTextField txtJugador3;
    private javax.swing.JTextField txtJugador4;
    private javax.swing.JTextField txtJugador5;
    private javax.swing.JTextField txtJugador6;
    private javax.swing.JTextField txtJugadorEscalera;
    private javax.swing.JTextField txtJugadorFull;
    private javax.swing.JTextField txtJugadorGenerala;
    private javax.swing.JTextField txtJugadorPoker;
    private javax.swing.JLabel txtMostrarNombreLabel;
    private javax.swing.JLabel txtMostrarNombreLabel2;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration                   

}
